### ISSUE TITLE
Error Loading Critters

### ISSUE THREAD

**Issue by grant** [shama/voxel-critter#6]
Is this project still alive?

I tried the demo and couldn't load other pictures.

```
XMLHttpRequest cannot load http://maxcors.jit.su/http://max.ic.ht/critters/_all_docs?include_docs=true. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://shama.github.io' is therefore not allowed access. 
```

**Comment by shama** [comment]
@maxogden is maxcors.jit.su no more?

@grant You can still load in critters and use this library. Without the above, the demo just won't load critters from voxelbuilder.com.

**Comment by max-mapper** [comment]
it is now cors.maxogden.com
