### ISSUE TITLE
Node compatibility 

### ISSUE THREAD

**Issue by max-mapper** [shama/voxel-critter#7]
@mikolalysenko is trying to hook up his orthogami repo up to critter data but there's no way to run this in node atm

About to board a plane or is start hacking on it

**Comment by shama** [comment]
Which part needs to be node compatible? The `convertToVoxels` part?

**Comment by max-mapper** [comment]
yes, sorry, just the part that reads the png into a canvas and extracts the voxel + color data

**Comment by mikolalysenko** [comment]
Awesome!
